# VERSION 1.0
# AUTHOR:         zhengxiaochuan <zhengxiaochuan-3@163.com>
# DESCRIPTION:    ngx_openresty
# TO_BUILD:       docker build -rm -t ngx_openresty .
<<<<<<< HEAD
# TO_RUN:         docker run -d --name jip-auth -p 5555:5555 -p 6666:6666 -v /home/CaaS/jip-auth/auth/conf/:/usr/local/openresty/nginx/conf/ -v /home/CaaS/jip-auth/auth/lua/:/usr/local/openresty/nginx/lua --link jip-registry:jip-registry   jip-auth
=======
# TO_RUN:         docker run -p hostport:80 -v /usr/local/openresty/nginx/conf/:/usr/local/openresty/nginx/conf/ -v /usr/local/openresty/nginx/lua/:/usr/local/openresty/nginx/lua/ -d ngx_openresty
>>>>>>> 2d9228c4452cb2410f5d9fd34edf13a69eb0c42a

FROM ubuntu:14.04
ENV DEBIAN_FRONTEND noninteractive

# nginx
RUN apt-get update -q \
    && apt-get install -yf build-essential python-software-properties software-properties-common \
    && add-apt-repository ppa:nginx/stable \
    && apt-get update -q \
    && apt-get -y install -y curl \
    && apt-get -y install perl

# build nginx from source with http auth module enabled
RUN apt-get -y install libpcre3-dev zlib1g-dev libssl-dev

# Add source code
ADD . /jip-auth

WORKDIR /jip-auth/openresty/

# Compile source code
RUN /usr/bin/env perl configure --with-http_ssl_module --with-http_auth_request_module
RUN chmod +x build/install
RUN make
RUN make install

# Run nginx
ENTRYPOINT /usr/local/openresty/nginx/sbin/nginx -c /usr/local/openresty/nginx/conf/nginx.conf && /bin/bash && sleep 9999d


# share /export/
VOLUME ["/export/log/"]
VOLUME ["/export/data/"]
VOLUME ["/export/conf/"]
#VOLUME ["/usr/local/openresty/nginx/conf/"]
#VOLUME ["/usr/local/openresty/nginx/lua/"]

# put self signed ssl key (generated by htpasswd
# RUN apt-get -y install apache2-utils
RUN cp /jip-auth/auth/conf/server.crt /etc/ssl/certs/docker-registry
RUN cp /jip-auth/auth/conf/server.key /etc/ssl/private/docker-registry

# nginx configuration
# follow https://github.com/docker/docker-registry/tree/master/contrib/nginx

#ADD nginx/nginx.conf /usr/local/openresty/nginx/conf/nginx.conf
#ADD nginx/docker-registry.htpasswd /usr/local/openresty/nginx/conf/docker-registry.htpasswd
#ADD nginx/docker-registry.conf /usr/local/nginx/conf/docker-registry.conf
#RUN mkdir /usr/local/openresty/nginx/conf/sites-enabled/
#ADD nginx/nginx.default /usr/local/openresty/nginx/conf/sites-enabled/default


EXPOSE 80 443
